version: '3.9'

services:
  phrinifluent_telegram_bot:
    image: phrinifluent_bot_image
    volumes:
      - ./:/app
    build: .
    container_name: phrinifluent_bot_container
    env_file:
      - .env
    restart: unless-stopped
